<?php

declare(strict_types=1);

namespace In2code\In2mcp\Domain\Mcp\Tool\Page;

use In2code\In2mcp\Domain\Mcp\Tool\AbstractTool;
use In2code\In2mcp\Domain\Repository\PageRepository;
use In2code\In2mcp\Domain\Service\DataHandlerService;

class CreatePageTool extends AbstractTool
{
    public function __construct(
        private readonly DataHandlerService $dataHandlerService,
        private readonly PageRepository $pageRepository,
    ) {
    }

    public function getName(): string
    {
        return 'create_page';
    }

    public function getDescription(): string
    {
        return 'Creates a new page below a given parent page. The slug is generated by TYPO3 unless it is given'
            . ' in "fields". Call "get_schema" for the available page types and fields, and look at a comparable'
            . ' existing page with "get_page" first to follow the conventions of this installation.';
    }

    public function getParameters(): array
    {
        return [
            'parentPageUid' => [
                'type' => 'integer',
                'description' => 'Uid of the page the new page is created in',
                'required' => true,
            ],
            'title' => [
                'type' => 'string',
                'description' => 'Title of the new page',
                'required' => true,
            ],
            'doktype' => [
                'type' => 'integer',
                'description' => 'Page type, 1 is a standard page',
                'default' => 1,
            ],
            'position' => [
                'type' => 'string',
                'description' => 'Whether the page becomes the last or the first child of the parent page',
                'enum' => ['end', 'start'],
                'default' => 'end',
            ],
            'afterPageUid' => [
                'type' => 'integer',
                'description' => 'Optional uid of a sibling page the new page is inserted behind. Overrides'
                    . ' "position" when greater than 0.',
                'default' => 0,
            ],
            'fields' => [
                'type' => 'object',
                'description' => 'Any further page fields, for example nav_title, subtitle, slug, description,'
                    . ' seo_title, hidden or backend_layout',
                'default' => [],
            ],
        ];
    }

    public function execute(array $arguments): array
    {
        $afterPageUid = $this->getIntArgument($arguments, 'afterPageUid');
        $fields = $this->getArrayArgument($arguments, 'fields');
        $fields['title'] = $this->getStringArgument($arguments, 'title');
        $fields['doktype'] = $this->getIntArgument($arguments, 'doktype');

        $uid = $this->dataHandlerService->createRecord(
            PageRepository::TABLE_NAME,
            $this->getPid(
                $this->getIntArgument($arguments, 'parentPageUid'),
                $afterPageUid,
                $this->getStringArgument($arguments, 'position')
            ),
            $fields
        );

        return [
            'created' => true,
            'pageUid' => $uid,
            'page' => $this->pageRepository->findByUid($uid),
        ];
    }

    /**
     * DataHandler puts a record with a positive pid at the very beginning of the target. To append a page at the
     * end, it has to be inserted behind the last existing sibling, which is expressed by a negative pid.
     */
    private function getPid(int $parentPageUid, int $afterPageUid, string $position): int
    {
        if ($afterPageUid > 0) {
            return -$afterPageUid;
        }

        if ($position === 'start') {
            return $parentPageUid;
        }

        $lastChildUid = $this->pageRepository->findLastChildUid($parentPageUid);
        return $lastChildUid > 0 ? -$lastChildUid : $parentPageUid;
    }
}
