<?php

declare(strict_types=1);

namespace In2code\In2mcp\Domain\Repository;

use Doctrine\DBAL\Exception;
use InvalidArgumentException;
use Psr\Log\LoggerInterface;
use TYPO3\CMS\Core\Cache\Frontend\FrontendInterface;
use TYPO3\CMS\Core\Crypto\PasswordHashing\InvalidPasswordHashException;
use TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashFactory;
use TYPO3\CMS\Core\Crypto\Random;
use TYPO3\CMS\Core\Database\Connection;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Utility\MathUtility;

/**
 * Finds the backend user that belongs to a given MCP api key. A key names its user, so exactly one salted hash
 * is verified per request - see splitApiKey() for why that matters.
 */
readonly class BackendUserRepository
{
    public const API_KEY_FIELD = 'in2mcp_apikey';

    /**
     * Separates the user part from the secret part of an api key. It is not part of the alphabet the secret is
     * built from, so the two can never be confused.
     */
    public const API_KEY_SEPARATOR = '.';

    private const TABLE_NAME = 'be_users';

    /**
     * Cache entry holding the hash an unknown key is verified against. Its content is the hash of a random
     * string that is thrown away, so there is nothing secret about it - it only has to be a hash the
     * installation produces itself, so that verifying it costs exactly as much as verifying a real one.
     */
    private const DUMMY_HASH_CACHE_ENTRY = 'in2mcp-dummy-hash';

    public function __construct(
        private ConnectionPool $connectionPool,
        private PasswordHashFactory $passwordHashFactory,
        private FrontendInterface $hashCache,
        private Random $random,
        private LoggerInterface $logger,
    ) {
    }

    public function findByApiKey(string $apiKey): ?array
    {
        if ($apiKey === '') {
            throw new InvalidArgumentException('MCP api key must not be empty', 1756800100);
        }

        [$backendUserUid, $secret] = $this->splitApiKey($apiKey);

        $backendUser = $this->findByUid($backendUserUid);

        // A request for a user that has no key must cost the same as one for a user that has: without this the
        // answer time tells an attacker exactly which backend users an api key was created for.
        $hashedApiKey = $backendUser === null
            ? $this->getDummyHash()
            : (string)($backendUser[self::API_KEY_FIELD] ?? '');

        if ($this->isApiKeyOfBackendUser($secret, $hashedApiKey) === false) {
            return null;
        }

        return $backendUser;
    }

    /**
     * A hash of a random string, kept in the hash cache. It is generated by the installation itself, so it uses
     * the algorithm and the cost that are configured here - a hardcoded hash would be verified faster or slower
     * than a real one and would leave the difference it is meant to remove.
     */
    private function getDummyHash(): string
    {
        $dummyHash = $this->hashCache->get(self::DUMMY_HASH_CACHE_ENTRY);
        if (is_string($dummyHash) && $dummyHash !== '') {
            return $dummyHash;
        }

        try {
            $dummyHash = $this->passwordHashFactory->getDefaultHashInstance('BE')->getHashedPassword(
                $this->random->generateRandomHexString(64)
            );
        } catch (InvalidPasswordHashException $exception) {
            $this->logger->warning('MCP: No hash instance available: ' . $exception->getMessage());
            return '';
        }

        $this->hashCache->set(self::DUMMY_HASH_CACHE_ENTRY, $dummyHash);
        return $dummyHash;
    }

    /**
     * An api key names the backend user it belongs to, so exactly one hash has to be verified per request.
     *
     * Without that the only way to find the user would be to verify the key against the hash of every user
     * that has one. Hashing is deliberately slow, so that turns the unauthenticated endpoint into a lever:
     * every wrong key costs one full hash per api key user, and the cost grows with every editor that gets a
     * key.
     *
     * @return array{0: int, 1: string} Uid of the backend user and the secret part of the key
     * @throws InvalidArgumentException
     */
    private function splitApiKey(string $apiKey): array
    {
        $position = strpos($apiKey, self::API_KEY_SEPARATOR);
        if ($position === false) {
            throw new InvalidArgumentException(
                'MCP api key has no user part. Keys created before this format are not valid any more, create'
                . ' a new one with the command "in2mcp:apikey".',
                1756801900
            );
        }

        $backendUserUid = substr($apiKey, 0, $position);
        if (MathUtility::canBeInterpretedAsInteger($backendUserUid) === false) {
            throw new InvalidArgumentException('MCP api key has no valid user part', 1756801904);
        }

        return [(int)$backendUserUid, substr($apiKey, $position + 1)];
    }

    /**
     * @throws Exception
     */
    private function findByUid(int $uid): ?array
    {
        if ($uid < 1) {
            return null;
        }

        $queryBuilder = $this->connectionPool->getQueryBuilderForTable(self::TABLE_NAME);

        try {
            $backendUser = $queryBuilder
                ->select('*')
                ->from(self::TABLE_NAME)
                ->where(
                    $queryBuilder->expr()->eq(
                        'uid',
                        $queryBuilder->createNamedParameter($uid, Connection::PARAM_INT)
                    ),
                    $queryBuilder->expr()->neq(
                        self::API_KEY_FIELD,
                        $queryBuilder->createNamedParameter('')
                    )
                )
                ->setMaxResults(1)
                ->executeQuery()
                ->fetchAssociative();
        } catch (Exception $exception) {
            $this->logger->error('MCP: Backend user could not be read: ' . $exception->getMessage());
            return null;
        }

        return $backendUser === false ? null : $backendUser;
    }

    /**
     * @throws Exception
     */
    public function findByUidOrUsername(string $identifier): ?array
    {
        $queryBuilder = $this->connectionPool->getQueryBuilderForTable(self::TABLE_NAME);
        $constraint = MathUtility::canBeInterpretedAsInteger($identifier)
            ? $queryBuilder->expr()->eq('uid', $queryBuilder->createNamedParameter((int)$identifier, Connection::PARAM_INT))
            : $queryBuilder->expr()->eq('username', $queryBuilder->createNamedParameter($identifier));

        $backendUser = $queryBuilder
            ->select('*')
            ->from(self::TABLE_NAME)
            ->where($constraint)
            ->setMaxResults(1)
            ->executeQuery()
            ->fetchAssociative();

        return $backendUser === false ? null : $backendUser;
    }

    /**
     * @throws Exception
     */
    public function updateApiKey(int $backendUserUid, string $hashedApiKey): void
    {
        $this->connectionPool->getConnectionForTable(self::TABLE_NAME)->update(
            self::TABLE_NAME,
            [self::API_KEY_FIELD => $hashedApiKey],
            ['uid' => $backendUserUid]
        );
    }

    private function isApiKeyOfBackendUser(string $apiKey, string $hashedApiKey): bool
    {
        if ($hashedApiKey === '') {
            return false;
        }

        try {
            return $this->passwordHashFactory->get($hashedApiKey, 'BE')->checkPassword($apiKey, $hashedApiKey);
        } catch (InvalidPasswordHashException $exception) {
            $this->logger->warning('MCP: Api key with an unsupported hash is ignored: ' . $exception->getMessage());
            return false;
        }
    }
}
